server/config.example.js

added config.example.js to the server folder as a placeholder for config elements.

Added config example file for ease of use

---

client/src/components/App.jsx
client/src/components/ProductDetailPage.jsx
client/src/index.jsx
package-lock.json
package.json
server/index.js

Refactored the app structure to use react router. 
This makes several structural changes. 
1. I moved everything out of index except for the initial mount. 
2. I moved App to it's own component
3. I added an initial product details component
4. The URL to see a product details is now required as http://<baseurl>:3000/product/<product id>
5. In the server, when the above url is contacted, this serves back the app.

React router refactor

---

package-lock.json
package.json
webpack.config.js

css-loader@^6.2.0 
style-loader@^3.2.1
Make sure to npm install after you pull this update from main
@alexanderolvera @asheliz648 @OjeikuA

Added new dependencies for use with webpack

---

client/src/components/ProductDetailPage.jsx
package-lock.json
package.json
tests/components/App.test.js
tests/components/ProductDetailPage.test.js

I have adapted the previous research branch test_framework_setup to be more inline with our current repo now that we are using react router. 
Some extra boiler is required to run components that may be expecting changes due to routing. So I have made two test files, one that requires routing and includes all code necessary and one that does not require routing. 
- Initial testing file for the App component (does not require routing)
- Initial testing file for the Product detail page (requires routing)
New modules installed to facilitate these changes
- @testing-library/jest-dom
- @testing-library/react
- msw
- regenerator-runtime

Completed initial testing setup for react/react-router components

---

client/src/components/App.jsx
client/src/components/ProductDetailPage.jsx

With the old method, the route accepted a property for a component. 
This new change allows for greater control on rendering multiple components on route or any other jsx we need to add. 
I also had to modify how params are accessed on the product detail component. Please refer to this new method if necessary on your components.

Updated the single current route to allow multiple components to be rendered

---

client/src/components/MainImageGallery.jsx
client/src/styles.css

Completed basic implementation fo a working carousel for the main gallery. 
WIP items:
- Still need to find a way to test this functionality with RTL. Currently I can verify visusally but overflowed items can not be tested with .toBeVisible so this may need some more research or refactoring. 
- The top index value used to keep track of the carousel position is not being reset when the style changes. This is an interaction with a separate component and will need more research. 
- I added a new attribute to the main css file for hidden items. I do intend to move all of my css to their own files soon. This is temporary.

Added a Product Gallery Carousel to the main gallery

---

client/src/components/relatedProducts/Comparison.jsx
merging changes

Modals currently displaying correct data: 
*displaying data values for current product and related product
* if characteristic does not exist, the value will be empty but characteristic name will still show
* no duplicate characteristic names
things to work on after deployment: 
* still will need to implement green check mark for true values 
* still will need to work on scrolling if list is long
* css/centering the modal/text

Comparison Modal : Displaying product names and characteristics

---

client/src/PDComponents/ProductDetailFooter.jsx
client/src/PDComponents/ProductDetailPage.jsx
client/src/PDComponents/styles/ProductDetailFooter.css

Just some small changes here
- Added the slogan to the product overview footer
- Added a dedicated css file for the footer. Updated some styles.

Overview description

---

client/src/components/App.jsx
server/index.js

This branch fixes the URL schema to match what Alex(other) had requested the other day in slack. 
Pattern is now <somesite>/<productId> instead of <somesite>/product/<productid>
BE AWARE, any tests you may have that require a react router wrapper, may need to be updated to conform to the new schema.

Url schema refactor

---

client/src/components/relatedProducts/ProductCard.jsx

Changes: 
- Modified the onClick of a related product card to match the updated url schema.

Fix link to product in Related Products

---

client/src/components/App.css
client/src/components/App.jsx

Added a new css file for App. This currently only contains very simple centering for the root div.

Simple styling to get the page centered

---

client/src/PDComponents/ProductCheckout.jsx
tests/components/PDComponents/ProductCheckout.test.js

Removing the favorite button in the Overview because it is not expressed as required in the Documentation, only in the wireframe. 
I feel the time it will take to get this button updating with the related products component is out of scope this late into the project.

Removed the favorite button and functionality/tests from Overview

---

server/index.js

Changes: 
- Added a new redirect to the server for the default route. Now redirects to a product page, 47421.
- Just to make the app load something while in dev instead of just a title page

Added default route redirect to a product page

---

server/index.js

Fixed productDetail API so that comparison modal and outfit list was working again

Update index.js (ProductDetail API fix)

---

client/src/PDComponents/MainImageGallery.jsx
client/src/PDComponents/ProductDescription.jsx
client/src/PDComponents/ProductDetailPrice.jsx
client/src/PDComponents/ProductStyleSelector.jsx
client/src/PDComponents/SubImageCarousel.jsx
client/src/PDComponents/styles/MainImageGallery.css
client/src/PDComponents/styles/ProductDescription.css
client/src/PDComponents/styles/ProductDetailPrice.css
client/src/PDComponents/styles/ProductStyleSelector.css

Updated various styles for the entire module. Mostly font changes and small spacing adjustments

Overview styles

---

client/src/components/App.jsx
client/src/components/StyledComponents/GlobalTheme.jsx
client/src/components/StyledComponents/Themes.jsx
client/src/components/StyledComponents/Toggle.jsx

* moon and sun toggling correctly
* chose a lighter purple hue among the same color class as the header color
* changed dark mode background to #181818 (darker gray) from #252426 (dark gray)

Darkmodez 

---

client/src/PDComponents/MainImageGallery.jsx
client/src/PDComponents/ProductDescription.jsx
client/src/PDComponents/ProductDetailFooter.jsx
client/src/PDComponents/ProductDetailPage.jsx
client/src/PDComponents/StyleSelectorItem.jsx
client/src/PDComponents/styles/MainImageGallery.css
client/src/PDComponents/styles/ProductDetailFooter.css
client/src/components/App.css
client/src/components/App.jsx
client/src/components/NavBar.css
client/src/components/StyledComponents/Themes.jsx

Changes: 
- Updated styles for the Overview Module(spaceing, dark/light mode)
- Added bubble borders to Overview components
- fixed an issue with the gallery modal but encapsulating the app in another div. 
- The above also solves a squeezing issue for the entire app centering.

Dark mode overview styles

---

client/src/components/App.jsx
client/src/components/NavBar.css
client/src/components/NavBar.jsx
client/src/components/StyledComponents/Toggle.jsx

Changes: 
- Updated the toggle styles
- Centered all items in the nav

Toggle in nav

---

client/src/components/NavBar.css
client/src/components/StyledComponents/Toggle.jsx

Changes: 
- Updated the toggle theme button with a label for accessibility 
- Re-styled the search bare for accessibility

Nav Accessibility changes

---

client/src/components/Review Widget/ModalContainer.jsx
client/src/components/Review Widget/PhotoThumbnailRow.jsx
client/src/components/Review Widget/ReviewSection.jsx
client/src/components/Review Widget/ReviewStars.jsx

alt tags  and header fix for improving accessbility

Alt tags review

---

client/src/QAComponents/AnswerList.jsx
client/src/QAComponents/NewAnswer.jsx
client/src/QAComponents/QAList.jsx
client/src/QAComponents/Question.jsx

Largely CSS-based changes for better dark mode readability

Questions and answers6
